### ISSUE TITLE
Hardware video acceleration / GPU drivers for AMD system

### ISSUE THREAD

**Issue by vishwa5854** [xerolinux/xero_iso#11]
I have installed XeroLinux and been using it as my daily driver for almost one and half month at this point, one major let down I have right now is no hardware encoding / acceleration available out of the box, which is hurting the performance of my machine during OBS recording sessions where something huge is running in the background with a lot of CPU utilization, performance drops very aggressively and it reaches a point where I couldn't use the desktop any more. 

Can you include hardware acceleration out of the box like MacOS for the next release probably??

**Comment by TechXero** [comment]
Hey there

You must be new to Linux otherwise you wouldn't be posting about this. 

Let me start by welcoming you to XeroLinux. That being said, this Distro will never include pre-installed drivers. That's why if look closely at the tool, there's a button that will take you straight to the GPU drivers install page where you can do that. 

I explained in a recent video that if I included all drivers users request on ISO out the box it would bloat to over 20gb we don't want that now do we? You just need to install the right drivers and you off to the races....

Good luck..m

**Comment by vishwa5854** [comment]
Understood. I used mhwd before but I just forgot about it.

**Comment by TechXero** [comment]
> Understood. I used mhwd before but I just forgot about it.

I can't believe you been using Xero all this time without Drivers lol....
